# Generated by Django 3.0.5 on 2020-09-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('qqEmail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('introduce', models.TextField()),
                ('startTime', models.CharField(max_length=15)),
                ('deadLine', models.CharField(max_length=15)),
                ('acceptTime', models.CharField(max_length=15)),
                ('startDep', models.IntegerField()),
                ('receiveDep', models.IntegerField()),
                ('fileAddress', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doneTime', models.CharField(max_length=15)),
                ('doneFileAddress', models.CharField(max_length=100)),
                ('doneFileName', models.CharField(max_length=100)),
                ('zanList', models.CharField(max_length=12)),
                ('message', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Task')),
            ],
        ),
    ]
