# Generated by Django 3.0.5 on 2020-09-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_done_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceptTime',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
