# Generated by Django 3.0.5 on 2020-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200905_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='doneTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='acceptTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadLine',
            field=models.DateTimeField(),
        ),
    ]
