# Generated by Django 3.0.5 on 2020-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200907_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceptTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
