# Generated by Django 3.1.1 on 2020-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200907_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='zanList',
            field=models.CharField(default='100', max_length=12),
        ),
    ]
